### ISSUE TITLE
Feature request: Allow to modify the database

### ISSUE THREAD

**Issue by FTPam** [askvortsov1/flarum-auto-moderator#1]
### description
I think a feature that can make this extension even more powerful is to allow data interaction with specific tables, specific columns, and specific rows. This is very beneficial for the extension to interact with other extensions and programs

### for example
When a user's email passed regex test, set column 'is_id_verified' to true. 

### benifit
In this way, my other associated systems, such as the Minecraft server, can also read this data to achieve the most convenient interaction between Flarum and other systems.

**Comment by askvortsov1** [comment]
> ### description
> I think a feature that can make this extension even more powerful is to allow data interaction with specific tables, specific columns, and specific rows. This is very beneficial for the extension to interact with other extensions and programs
> 
> ### for example
> When a user's email passed regex test, set column 'is_id_verified' to true. 
> 
> ### benifit
> In this way, my other associated systems, such as the Minecraft server, can also read this data to achieve the most convenient interaction between Flarum and other systems.

I would prefer to keep the default features in this extension use case driven. However, this extension is designed to be extensible, so you could relatively easily add an action that sets verified status through another extension.
